

###
POST http://localhost:3000/register HTTP/1.1
Content-Type: application/json

{
"email": "test1@test.com", "password": "1234567890"
}
###
POST http://localhost:3000/login HTTP/1.1
Content-Type: application/json

{
"email": "test1@test.com", "password": "1234567890"
}

//------POST MODEL-----//
//READ
###
GET http://localhost:3000/posts/65a667f46176351c31ab141b HTTP/1.1

###
GET http://localhost:3000/posts/allPosts HTTP/1.1

###
POST http://localhost:3000/posts/add-post HTTP/1.1
Content-Type: application/json

{
    "user": "5f9f5b3b1c1d4cafa959dcf2",
    "title": "test",
    "body": "test",
    "comments": "65a6644d07a1ba2d560112e6",
    "likes": "65a6644d07a1ba2d560112e7"
}
  
###
PUT http://localhost:3000/posts/65a667f46176351c31ab141b/update HTTP/1.1
Content-Type: application/json

{
    "title": "update title",
    "body": "update body",
    "comments": "",
    "likes": ""

}

###
DELETE http://localhost:3000/posts/65a667f46176351c31ab141b HTTP/1.1

