
POST http://localhost:3000/register HTTP/1.1
Content-Type: application/json

{
"email": "test1@test.com", "password": "1234567890"
}

POST http://localhost:3000/register HTTP/1.1
Content-Type: application/json

{
"email": "test1@test.com", "password": "1234567890"
}

//------POST MODEL-----//
//READ
###
GET http://localhost:3000/posts/65a3f0c6c1d4cafa959dcf32 HTTP/1.1

